# Generated by Django 5.1 on 2024-08-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_added_by_global_name_todo_added_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_by_global_name',
        ),
    ]
